function [A]=new_plot(t,d,a,alp)
A=[cosd(t) -sind(t)*cosd(alp) sind(t)*sind(alp) a*cosd(t);...
    sind(t) cosd(t)*cosd(alp) -cosd(t)*sind(alp) a*sind(t);...
    0 sind(alp) cosd(alp) d;...
    0 0 0 1];



